### ISSUE TITLE
Cannot import BibliographicRecordServiceConfig following 'Change the permissions' docu

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/docs-invenio-rdm#116]
Package version (if known): <version>

`invenio-cli, version 0.22.0`

## Describe the bug

Following the instructions given here:
https://github.com/inveniosoftware/docs-invenio-rdm/blob/e9b1bcfe0b34594a4acbdc0a2add3c19d8db52fa/docs/develop/make_it_your_own.md#modify-inveniocfg

I get the following error:

```
ImportError: cannot import name 'BibliographicRecordServiceConfig' from 'invenio_rdm_records.services' (/home/chriz/rz/git/invenio/icli-0-22-0/venv/lib/python3.7/site-packages/invenio_rdm_records/services/__init__.py)
```

## Steps to Reproduce
1. Follow the steps here: https://inveniordm.docs.cern.ch/develop/ until you can run it (`invenio-cli run`).
2. Then follow the steps here: https://inveniordm.docs.cern.ch/develop/make_it_your_own/#modify-inveniocfg - that is:
    - adjusting the `invenio.cfg`
    - rerun `invenio-cli run`
3. See error
```
ImportError: cannot import name 'BibliographicRecordServiceConfig' from 'invenio_rdm_records.services' (/home/chriz/rz/git/invenio/icli-0-22-0/venv/lib/python3.7/site-packages/invenio_rdm_records/services/__init__.py)
```
## Expected behavior

`invenio-cli run` goes through without errors and permissions are set as described.

## Additional context

`BibliographicRecordServiceConfig` was recently renamend (and moved?). Possible fix:

```python
from invenio_rdm_records.services import RDMRecordPermissionPolicy
from invenio_rdm_records.services.config import RDMRecordServiceConfig
from invenio_records_permissions.generators import SuperUser


class MyRecordPermissionPolicy(RDMRecordPermissionPolicy):
    can_create = [SuperUser()]


class MyBibliographicRecordServiceConfig(RDMRecordServiceConfig):
    permission_policy_cls = MyRecordPermissionPolicy


RDM_RECORDS_BIBLIOGRAPHIC_SERVICE_CONFIG = MyBibliographicRecordServiceConfig
```

I'm preparing a PR.

**Comment by zzacharo** [comment]
fixed by https://github.com/inveniosoftware/docs-invenio-rdm/pull/117
