### ISSUE TITLE
Replacing BibliographicRecordServiceConfig with RDMRecordServiceConfig in text

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/docs-invenio-rdm#118]
Following up on #116 there is a second place in the [docu](https://github.com/inveniosoftware/docs-invenio-rdm/blob/e9b1bcfe0b34594a4acbdc0a2add3c19d8db52fa/docs/develop/make_it_your_own.md#modify-inveniocfg) where `BibliographicRecordServiceConfig` is mentioned.

I will send a PR to fix it.

**Comment by zzacharo** [comment]
fixed by https://github.com/inveniosoftware/docs-invenio-rdm/pull/119
