### ISSUE TITLE
Adjusting the record-landing-page fails

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/docs-invenio-rdm#131]
Package version (if known):
`invenio-cli, version 0.22.0`

## Describe the bug / Steps to Reproduce
Following the instructions here:
https://inveniordm.docs.cern.ch/customize/styling/#change-the-record-landing-page
doesn't change the record-landing-page.

## Expected behavior

The record landing page is adjusted.

## Additional context

For me the issue is in the folder-path:
```
To override the record landing page, add the following folders and file in your templates/ folder: invenio_app_rdm/records/detail.html.
```

It works if I add the `semantic-ui` directory:

```
icli-0-23-0-dev/templates$ tree -a
.
├── .gitkeep
└── semantic-ui
    └── invenio_app_rdm
        └── records
            └── detail.html
```

I'm not sure whether this is an error in the documentation or the implementation. Since https://inveniordm.docs.cern.ch/customize/styling/#change-other-pages says explicitely to 'exclude' the `semantic-ui`-folder: `Copy the filepath relative to templates/semantic-ui/ in invenio-app-rdm into your instance's templates/ folder. `

**Comment by fenekku** [comment]
That was an error in the documentation. A recent PR by @florianfranz rectifies this (and I will also fix the reference in `#change-other-pages`. Thanks for reporting!
