### ISSUE TITLE
Typos/broken links/documentation errors on Features and Install pages: v6-release (2021/08/06)

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/docs-invenio-rdm#218]
While reading the Features and Install pages I found the following issues:

https://inveniordm.docs.cern.ch/features/

- [x] #219
- [x] #220

https://inveniordm.docs.cern.ch/install/
- [x] #221
- [x] #222
- [x] #223
  Is: 'Local application with containerized services (good for developers or if want to customize InvenioRDM).'
  Should: 'Local application with containerized services (good for developers or if you want to customize InvenioRDM).'
- [x] #224

https://inveniordm.docs.cern.ch/install/requirements/

- [x] I'm not a Mac user. Should this be one or two lines? `SYSTEM_VERSION_COMPAT=1 invenio-cli install`
- [x] #225

https://inveniordm.docs.cern.ch/install/scaffold/
- [x] #226

  ```
  Select development_tools:
  1 - yes
  2 - no
  Choose from 1, 2 [1]:
  ```

https://inveniordm.docs.cern.ch/install/build-setup-run/

- [x] For the impatient / Container:
  ```
  export INVENIO_SITE_UI_URL=https://https://127.0.0.1
  export INVENIO_SITE_API_URL=https://https://127.0.0.1/api
  ```
  I think we discussed that this doesn't work, because the variables are not landing in the container.
  Changing in the invenio.cfg works.
- [x] Missing dot: 'Load fixtures data into InvenioRDM'
- [x] Missing 'a':
  Is: 'The local build steps involve installing all the Python dependencies into local Python virtual environment.'
  Should: 'The local build steps involve installing all the Python dependencies into a local Python virtual environment.'

https://inveniordm.docs.cern.ch/install/configuration/

- [x] Missing dot by 'e.g.':
  Is: 'In particular, you should NEVER set secrets or credentials in the configuration file, and you should NEVER commit that file to e.g a Git source code repository.'
  Should: 'In particular, you should NEVER set secrets or credentials in the configuration file, and you should NEVER commit that file to e.g. a Git source code repository.'
- [x] 'that' too much?:
  Is: 'Invenio has a configuration option called APP_ALLOWED_HOSTS which controls which hosts/domain names that can be served.'
  Should: 'Invenio has a configuration option called APP_ALLOWED_HOSTS which controls which hosts/domain names can be served.'
- [x] Missing 's' (website/websites)?:
  Is: 'The web server uses that for instance to host several website on the same domain.'
  Should: 'The web server uses that for instance to host several websites on the same domain.'
- [x] Missing 's' (host/hosts)?:
  Is: 'Normally your load balancer/web server should only route requests with a white-listed set of host to your application.'
  Should: 'Normally your load balancer/web server should only route requests with a white-listed set of hosts to your application.'
- [x] Missing dot: 'Use different secret keys for different deployments (testing, staging, production)'
- [x] work or works?
  'The load balancer and web server both works as proxies, which means that the clients remote address usually get’s added in the X-Forwarded-For HTTP header.'
- [x] get's is gets:
  'The load balancer and web server both works as proxies, which means that the clients remote address usually get’s added in the X-Forwarded-For HTTP header.'

https://inveniordm.docs.cern.ch/install/run/

- [x] Whitespace intended ' .'?: 'Navigate to https://127.0.0.1:5000 .'
- [x] Where is 'there'?: 'You can explore all the features there.'

Overall
- [ ] #228

**Comment by lnielsen** [comment]
Thanks a lot!!! I've fixed all but one issue which will be easier with a global search and replace :-) Fixes should soon be available on the docs site.

**Comment by lnielsen** [comment]
The line ``SYSTEM_VERSION_COMPAT=1 invenio-cli install`` is indeed intended to be a oneliner.
