### ISSUE TITLE
Use a release branch/tag as the automatic documentation site update 

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/docs-invenio-rdm#22]
The documentation site should only update on a new release. This way we can accumulate documentation changes as we move through the sprint and not confuse readers with documentation for a version of InvenioRDM that has not been released yet.

**Comment by ppanero** [comment]
Fixed.

Created branch `maint`. Now the https://inveniordm.docs.cern.ch only deploy what happens to `maint`. In addition, I have reset `maint` to point to the previous release docs, not to put helm stuff yet.
