### ISSUE TITLE
Background-color default gray on Linux Firefox

### ISSUE THREAD

**Issue by utnapischtim** [inveniosoftware/docs-invenio-rdm#26]
The Firefox on Linux uses normally gray as the background-color if no color is set explicitly

Firefox Linux
![user_documentation_gray_background_color_linux_firefox](https://user-images.githubusercontent.com/216565/75540209-dd33d580-5a1b-11ea-8082-17f58a524cef.png)

Firefox Windows
![user_documentation_white_background_color_windows_firefox](https://user-images.githubusercontent.com/216565/75540221-e15ff300-5a1b-11ea-8758-411a110f2e5d.png)

**Comment by fenekku** [comment]
@utnapischtim  Mmm what version of linux and firefox do you run? I run Ubuntu 18.04 and Firefox 73.0.1 and can't reproduce this. Silly question: do you have night mode on?

**Comment by utnapischtim** [comment]
@fenekku i use Gentoo and Firefox 73.0.1 (64-bit), default theme. 
Preferences->Language and Appearance->Color says something about system color, maybe there is something on Gentoos system colors which defaults to gray, seems strange to me.

when i uncheck 'use system colors' it is white

if no one else having the same problem i will close the issue

**Comment by fenekku** [comment]
Yeah... sorry about that. Nothing we can do there.
