### ISSUE TITLE
docs(I18N): how to contribute to translations

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/docs-invenio-rdm#266]
## Describe the solution you'd like
write the I18N documentation section from a contributor prospective.
The documentation should cover all the necessary steps that a contributor should take.
**Please note this documentation is not intend for maintainers rather for possible translator/reviewer of the language.**
* What steps should a contributor take for adding a new language or contributing to the existing languages.
* How to join the Transifex?
* How to join discord channel for translations?
* Add the list of invenioRDM used modules for transifex see [LIST](https://github.com/inveniosoftware/invenio-i18n/issues/99) **NOTE this list is not finalized**
* etc

## Additional context
please have a look into the screenshot for a possible location of the docs.
![docs-contributor](https://user-images.githubusercontent.com/44528277/143419282-3a303d2d-f1d1-469f-866a-e47024aea11d.png)

**Comment by chriz-uniba** [comment]
First (write protected) draft comes here: https://pad.gwdg.de/HU6IDyAESI-p1rgu3WtGAQ#

**Comment by chriz-uniba** [comment]
First github-draft: https://github.com/chriz-uniba/docs-invenio-rdm/tree/feature-translator-guide
Open questions still here: https://pad.gwdg.de/HU6IDyAESI-p1rgu3WtGAQ#

**Comment by mb-wali** [comment]
closed via inveniosoftware/docs-invenio-rdm/pull/286
