### ISSUE TITLE
Add search bar on first/home page

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/docs-invenio-rdm#267]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when I need to search something in the documentation:
On the 'home' page there is no search bar:
https://inveniordm.docs.cern.ch/
![image](https://user-images.githubusercontent.com/74763324/143838463-c08ab867-e367-4c78-b067-2d17ab77ec05.png)

So I need to click on one of the other tabs:
https://inveniordm.docs.cern.ch/features/
![image](https://user-images.githubusercontent.com/74763324/143838585-44b35a89-50d9-4188-9d4c-98fe868f4938.png)
To get my search bar.

## Describe the solution you'd like

Add the search-bar to the 'home' page.

**Comment by tmorrell** [comment]
Fixed by the amazing @Samk13 as part of the dark mode work
