### ISSUE TITLE
JS i18n section

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/docs-invenio-rdm#293]
Add a quick guide under either "Topic guides" or "How to guides" on how to integrate i18n in JS.

See: https://discord.com/channels/692989811736182844/852219787005919242/940240963937390623

**Comment by zzacharo** [comment]
Workflow on how to translate JS strings of a module described in https://github.com/inveniosoftware/invenio-app-rdm/blob/f56369fff8040089f327a9aa3d1a7d089a1692ce/.tx/config#L35

**Comment by zzacharo** [comment]
See https://github.com/inveniosoftware/docs-invenio-rdm/issues/285
