### ISSUE TITLE
Online docs website announces v9.0 release but v9.1 is out

### ISSUE THREAD

**Issue by mhucka** [inveniosoftware/docs-invenio-rdm#390]
## Describe the bug

Visiting <https://inveniordm.docs.cern.ch>, one finds a green-colored announcement box about the latest release of Invenio RDM. However, the current release is newer (9.1) than the release mentioned on the site (9.0). See near the bottom of the screenshot below:

<p align="center">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/1450019/179837218-52d83c50-0448-4bc6-a383-a96596ad3258.png">
</p>

## Expected behavior

The announcement box should probably mention and link to the [v9.1](https://inveniordm.docs.cern.ch/releases/versions/version-v9.1.0/) release notes instead of the v9.0 one.

## Screenshots (if applicable)

See above.

**Comment by ZedThree** [comment]
This should probably be updated for v10 now?
