### ISSUE TITLE
deploy docs-invenio-rdm-qa site

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/docs-invenio-rdm#431]
Once this [PR](https://gitlab.cern.ch/authoring/documentation/mkdocs-ci/-/merge_requests/3) is merged we can enable the deployment of a QA docs site. 
**Update**: Scheduled [OTG](https://cern.service-now.com/service-portal?id=outage&n=OTG0073912)

What will we need to do is:

- [ ] Create a new repo in our GitLab with GitHub sync, as done for https://gitlab.cern.ch/inveniosoftware/docs-invenio-rdm
- [ ] Change the default branch, pointing to the [dev](https://github.com/inveniosoftware/docs-invenio-rdm/tree/dev) branch here.
- [ ] Setup a new DOC site following CERN guide for the `qa` doc

**Comment by ntarocco** [comment]
Done: https://inveniordm-dev.docs.cern.ch
