### ISSUE TITLE
System requirements update elasticsearch/opensearch needed

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/docs-invenio-rdm#432]
The following lines need some update wrt. opensearch:

https://github.com/inveniosoftware/docs-invenio-rdm/blob/4e96e2e74eb6f307a117b3e1c2b373f5d8aca29e/docs/install/requirements.md?plain=1#L45-L48

**Comment by chriz-uniba** [comment]
Also here:

https://github.com/inveniosoftware/docs-invenio-rdm/blob/4e96e2e74eb6f307a117b3e1c2b373f5d8aca29e/docs/install/requirements.md?plain=1#L96-L115

**Comment by psaiz** [comment]
So, the first comment was indeed already addressed. The second one, about the requirements is not. Thanks for pointing this out!
I'll send a new PR to address it
