### ISSUE TITLE
Documentation: v11 release, upgrade guide

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/docs-invenio-rdm#447]
# cookiecutter
- document all upgrades
- invenio-pages run alembic upgrade to create pages See [PR](https://github.com/inveniosoftware/invenio-pages/pull/53)
- new configuration for the deposit template added by Sam [PR](https://github.com/inveniosoftware/invenio-app-rdm/pull/1988/files#diff-988eb51a0bc0a8bf6efd0b04d1bb6b6d8f24cc80504ea36699a202904a20af4dR543)
- new configuration for [record detail page](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/config.py#L676) template overridability.

# invenio-records-resources
- Breaking change: FieldsResolver.expand() method is changed to require an identity parameter.
- Breaking change: LinksTemplate.expand() method is changed to require an identity parameter.

# invenio-app-rdm
- CLI command for rebuilding the search indices: https://github.com/inveniosoftware/invenio-app-rdm/pull/1969
- Redirector rules: configuration to provide easy redirection of urls in RDM (https://github.com/inveniosoftware/invenio-app-rdm/pull/1994)

# deployment-docker-helm
- Python 3.9 required
- Node 16
- Docker images
- Helm and secrets

# invenio-accounts
- default global visibility settings: https://github.com/inveniosoftware/invenio-accounts/pull/430
- new flag to confirm user in cli: https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/cli.py#L50

# invenio-administration 
- docs: https://github.com/inveniosoftware/docs-invenio-rdm/pull/450

# invenio-records-resources
- Search fields parsing: added query parser at the application level  to allow retro-compatible fields aliases https://github.com/inveniosoftware/invenio-records-resources/pull/433

# oauth
- extra options
- groups?

# migration
- add `libpq-dev` in the list of requirements

**Comment by alejandromumo** [comment]
Introduced in https://github.com/inveniosoftware/invenio-app-rdm/pull/1975 : 

- Document new configurations for files integrity report:
```
FILES_REST_CHECKSUM_VERIFICATION_URI_PREFIXES = []
"""URI prefixes of files their checksums should be verified"""

FILES_INTEGRITY_REPORT_TEMPLATE = (
    "invenio_app_rdm/files_integrity_report/email/files_integrity_report.html"
)
"""Files integrity report template"""

FILES_INTEGRITY_REPORT_SUBJECT = "Files integrity report"
"""Files integrity report subject"""

ADMIN_EMAIL_RECIPIENT = "info@inveniosoftware.org"
"""Admin e-mail"""

MAIL_DEFAULT_SENDER = "info@inveniosoftware.org"
"""Default e-mail address sender."""

```

- Especially mention that `MAIL_DEFAULT_SENDER` is a config from [Flask-Mail](https://pythonhosted.org/Flask-Mail/), whose implications can be seen in [here](https://pythonhosted.org/Flask-Mail/#sending-messages) : 
`If you have set MAIL_DEFAULT_SENDER you don’t need to set the message sender explicity, as it will use this configuration value by default`

**Comment by alejandromumo** [comment]
Introduced in https://github.com/inveniosoftware/invenio-app-rdm/pull/1994:

- Document new configuration for redirector:
```
REDIRECTOR_RULES = {}
```

redirection rules can be added to this dictionary. 

I wrote usage examples in the resource's [docstring](https://github.com/inveniosoftware/invenio-app-rdm/blob/508e8c22c77c1c3704399878668ee1f186f477f6/invenio_app_rdm/redirector/resource.py#L19)

Perhaps we should add a step by step HOW-TO guide in the docs.

**Comment by alejandromumo** [comment]
`invenio-records-resources` might need to be released with a new major following the changes in https://github.com/zenodo/zenodo-rdm/issues/102

**Comment by zzacharo** [comment]
> `invenio-records-resources` might need to be released with a new major following the changes in [zenodo/zenodo-rdm#102](https://github.com/zenodo/zenodo-rdm/issues/102)

there is no need as in the relevant [PR](https://github.com/inveniosoftware/invenio-records-resources/pull/433/files) there is no breaking change (plus the module has been bumped to major release compared to v10)
