### ISSUE TITLE
write documentation about events handling on the architecture

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/docs-invenio-rdm#482]
Add a section under https://inveniordm.docs.cern.ch/develop/ about event handling. Mention the current "back relations" or "change notifications", the "mail notifications". Mention the potential implementation of the event bus (future).

Once the work on stats has been done, add here how they are handled.

**Comment by ntarocco** [comment]
IMO main points to cover:
- what are the available patterns and APIs to trigger an action after an action
- what is the best practice for each of them
- when to use one or the other
- what's coming
