### ISSUE TITLE
Add documentation on how to enable reusable custom fields in an instance.

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/docs-invenio-rdm#502]
In the issue we should:

- Document how to import and enable reusable custom fields
  - e.g. enable [journal custom fields](https://github.com/inveniosoftware/invenio-rdm-records/issues/1191) 
  - A full example on how to configure custom fields and arrange them can be found in https://github.com/inveniosoftware/invenio-rdm-records/issues/1232
- Document newly introduced configurations (e.g. `hidden` attribute for custom fields configs)

**Comment by alejandromumo** [comment]
I think this is already covered in other documentations (e.g. ["Records custom fields[¶](https://inveniordm.docs.cern.ch/customize/custom_fields/records/#records-custom-fields)"](https://inveniordm.docs.cern.ch/customize/custom_fields/records/))

WDYT @kpsherva ?

**Comment by slint** [comment]
I think zoned-out during the stand-up, but here are a couple of ideas:

- Add a new top-level `Metadata` category, and with `Publishing information` and `Conference` sections, explaining how to add them, and what the impact is on the UI (deposit form + record landing page)
  - Could `Custom fields` be a sub-section of `Metadata` then?
- Add `Publishing information` and `Conference` sections under `Custom fields`

**Comment by slint** [comment]
Based on the metadata Zenodo right now, I don't see any more fields that we'll be adding as custom fields.

But e.g. CodeMeta fields would also fit under this section (and possibly any other contrib that comes up in the future). I wouldn't think of it as a "per-field", but more of a "conceptually similar set of fields". E.g. "Publishing information" includes journal, imprint, and thesis.

**Comment by alejandromumo** [comment]
Moved to approved as it was accepted by @ppanero
