### ISSUE TITLE
v12 release - Changelog

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/docs-invenio-rdm#536]
# Changes

- [x] react-invenio-deposit deprecation, change imports (from "react-invenio-deposit" to "@js/invenio-rdm-records")
- [ ] removed file options component and merged it in a base files component
- [x] invenio-pages: https://github.com/inveniosoftware/invenio-pages/pull/87
- [x] granting access to the record to users/group: https://github.com/CERNDocumentServer/cds-rdm/issues/109

# Upgrade guide

## Action

Figure out mapping versions and if they are correctly bumped. Goal is to not assume that we need to delete and recreate indices if possible e.g zenodo cannot do that once in production!

## Updated mappings

- [ ] added preferences.locale and preferences.timezone
With the following params in:
invenio_communities/members/records/mappings/os-v1/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/os-v1/communitymembers/members/member-v1.0.0.json
invenio_communities/members/records/mappings/os-v2/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/os-v2/communitymembers/members/member-v1.0.0.json
invenio_communities/members/records/mappings/v7/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
invenio_communities/members/records/mappings/v7/communitymembers/members/member-v1.0.0.json
https://github.com/inveniosoftware/invenio-communities/pull/938

- [ ] And also the following changes in these files:
invenio_users_resources/records/mappings/os-v1/users/user-v1.0.0.json
invenio_users_resources/records/mappings/os-v2/users/user-v1.0.0.json
invenio_users_resources/records/mappings/v7/users/user-v1.0.0.json
https://github.com/inveniosoftware/invenio-communities/pull/938

- [ ] files of the record (bumped record schema version to major, needs migration script)
- [ ] added community member `preferences.notifications` (https://github.com/inveniosoftware/invenio-communities/pull/952)
  - invenio_communities/members/records/mappings/os-v1/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
  - invenio_communities/members/records/mappings/os-v1/communitymembers/members/member-v1.0.0.json
  - invenio_communities/members/records/mappings/os-v2/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
  - invenio_communities/members/records/mappings/os-v2/communitymembers/members/member-v1.0.0.json
  - invenio_communities/members/records/mappings/v7/communitymembers/archivedinvitations/archivedinvitation-v1.0.0.json
  - invenio_communities/members/records/mappings/v7/communitymembers/members/member-v1.0.0.json
 
- [ ] added user `preferences.notifications` (https://github.com/inveniosoftware/invenio-users-resources/pull/65)
  - invenio_users_resources/records/mappings/os-v1/users/user-v1.0.0.json
  - invenio_users_resources/records/mappings/os-v2/users/user-v1.0.0.json
  - invenio_users_resources/records/mappings/v7/users/user-v1.0.0.json

- [ ] added group `description` (https://github.com/inveniosoftware/invenio-users-resources/pull/75/, moved description to v2 in https://github.com/inveniosoftware/invenio-users-resources/pull/85)
  - invenio_users_resources/records/mappings/os-v1/groups/group-v2.0.0.json
  - invenio_users_resources/records/mappings/os-v2/groups/group-v2.0.0.json
  - invenio_users_resources/records/mappings/v7/groups/group-v2.0.0.json
 
- [ ] media files new field (https://github.com/inveniosoftware/invenio-rdm-records/pull/1335/files#diff-657864537095f2081d49e2339b1f41c313e8ba37202941af034201a9aedc1bfc)
   - [ ] there are a couple changes coming with this, including added versioning in record files and media files (alembic recipe is added but is should be tests as part of the upgrade guide)
- [ ] access requests mappings changes and alembic recipes (https://github.com/inveniosoftware/invenio-rdm-records/pull/1306/files)

**Comment by kpsherva** [comment]
to be added to upgrade guide:  https://github.com/inveniosoftware/helm-invenio/commit/54a63a2cfd391ea5c0ea53c705977b49f84ca971

**Comment by zzacharo** [comment]
Changes in the interface of reindexing groups and users https://github.com/inveniosoftware/invenio-users-resources/pull/73/files#diff-51fb771cf55b10a362ae4be4483ef5cbfdc904cae4e24a6340aa3e4251db6062R21

**Comment by zzacharo** [comment]
Document notifications, inlcuding all new ones i.e member invitations and comments

**Comment by zzacharo** [comment]
check also https://github.com/inveniosoftware/invenio-app-rdm/issues/2343
