### ISSUE TITLE
requirements: Node version

### ISSUE THREAD

**Issue by dfdan** [inveniosoftware/docs-invenio-rdm#568]
Just making a quick note that https://inveniordm.docs.cern.ch/install/requirements/ still says node 14, but v11 prefers(/needs) 16 as specified here https://inveniordm.docs.cern.ch/releases/versions/version-v11.0.0/

I know check-requirements picks this up, but probably worth correcting?

**Comment by marcelomgarcia** [comment]
Just to add to this issue, now Node is version 20, but Invenio still asks from v16. Maybe the requirements page should be more specific about the version of Node.
