### ISSUE TITLE
temp versions removing?

### ISSUE THREAD

**Issue by utnapischtim** [inveniosoftware/docs-invenio-rdm#658]
https://inveniordm.docs.cern.ch/releases/temporary-versions/version-v12.0.0b1/

- should we remove the temp version migration and description?
- if we not remove it, we should at least put a big flag on it that users should use the real v12 release because there is one

**Comment by fenekku** [comment]
closed via https://github.com/inveniosoftware/docs-invenio-rdm/pull/706
