### ISSUE TITLE
Documentation: Review inveniordm.docs.cern.ch for Nov 11 changes

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/docs-invenio-rdm#76]
**IMPORTANT**: Note that there is a PR with quite some work already done.

- [x] Home
- [x] Install
- [x] Preview
- [x] Develop
    - [x] Getting started
    - [x] Install locally
    - [x] Run. --> Still missing to update the json dicts to the new data model
    - [x] Make it your own. --> Still missing to update json dicst and testing the customizations
    - [x] Edit a module --> **NEW** section to explain how to setup and develop CSS and React. Written, but not tested.
    - [x] Troubleshooting
    - [x] Cleanup
- [x] Extensions  --> No need for update. Should we use the new `module_install` to install the extension?
- [x] Deploy
    - [x] How to
    - [x] OpenShift
    - [x] K8
    - [x] System components
    - [x] Configuration
    - [x] Build your image
    - [x] Image registries
    - [x] Benchmarking

**Comment by ppanero** [comment]
This was closed due to my comment on the other PR. Re-opening since it still needs a second pass.

**Comment by ppanero** [comment]
Closed by 
#79 #78 #77
