### ISSUE TITLE
Update creators and contributors schema documentation for given/family names

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/docs-invenio-rdm#94]
Package version (if known): november release

Update https://inveniordm.docs.cern.ch/reference/metadata/#creators-1-n to indicate that for personal types the family name / given name is required while it is ignored for organizational type and vice-versa.

**Comment by dfdan** [comment]
Looks to me as if only 1 of given and family is required, which is probably most appropriate.

**Comment by cfgamboa** [comment]
Personal and organizational or Person and Organization, currently November release comes with the last ones.
I see on the demo at CERN this fields were also updated.
